Force curl to fail

diff --git a/gh-am b/gh-am
--- a/gh-am
+++ b/gh-am
@@ -2,6 +2,8 @@
 # Apply GitHub PRs with 'git-am'. This takes the patch URL as its first
 # argument, each subsequent argument is passed to the 'git am' command.
 
+argv0="$(basename $0)"
+
 if [ -z "$1" ]; then
 	>&2 printf "usage: gh-am [patch url] [flags...]\n"
 	exit 1
@@ -9,14 +11,17 @@ fi
 
 for b in curl git; do
 	if ! hash "$b"; then
-		>&2 printf "%s: requires %s\n" "$(basename $0)" "$b"
+		>&2 printf "%s: requires %s\n" "$argv0" "$b"
 		exit 1
 	fi
 done
 
 patch=$(mktemp)
 
-curl -s "$1" > "$patch"
+if ! curl -s -f "$1" > "$patch"; then
+	>&2 printf "%s: failed to curl patch url\n" "$argv0"
+	exit 1
+fi
 
 shift 1
 
